### PR TITLE
Load custom routes from theme folder

### PR DESCRIPTION
**Pull request by starsinmypockets**
Allow themes to extend routes app routes.

### CODE REVIEW

**Comment by anuveyatsu** [comment]
@starsinmypockets would it throw an error if you don't have `routes.js` module in your template? E.g, `opendk` and `eds` themes don't need custom routes.

**Comment by starsinmypockets** [comment]
Yes, for this implementation the theme would need a stub. I think this is not a bad pattern since the default theme template could include the placeholder which would serve as a guide for devs... We could add a try / catch that throws an error explaining that this file is required... or a warning..

**Comment by starsinmypockets** [comment]
(If this is approved I can add test coverage)

**Comment by starsinmypockets** [comment]
Closed. This will be picked up in this epic:
https://github.com/datopian/frontend-v2/issues/22

**Pull request closed without merging**
