### PR TITLE
Expose 'lib' and 'utils' to themes and plugins

### PR DESCRIPTION
**Pull request by anuveyatsu**
E.g., I'm developing a theme and I want to use `lib/dms.js` and `utils/index.js` modules. So in my theme `my-theme/index.js` I can do:

```javascript
module.exports = function (app) {
  const dms = app.get('dms')
  const config = app.get('config')
  const utils = app.get('utils')

 // Then I can use these to do my dev work
}
```

### CODE REVIEW

**Comment by anuveyatsu** [comment]
@nightsh thanks!

**Comment by rufuspollock** [comment]
@anuveyatsu this is great.

This seems really minor so np just a PR however in future I suggest

a) get an issue that this refers to (so it can get discussed quickly) - also easier to find than PRs in the future

b) i thought you can access the dms in your plugin already and in the theme -- can't you just require them?

**Comment by anuveyatsu** [comment]
@rufuspollock thanks for the feedback.

a) noted

b) you can if your theme/plugin is builtin into frontend-v2. If you want to have a standalone theme/plugin you can't require it - you only have `app` object passed

**Comment by anuveyatsu** [comment]
@rufuspollock UPDATE:

actually you could require it, e.g., your theme is a NPM package so from `node_modules/theme/index.js` you could `require('../../lib/dms')` but relative paths aren't so great, e.g., in your project the theme location can be different.

**Pull request merged**
