### PR TITLE
Use GET request for package retrieve.

### PR DESCRIPTION
**Pull request by sagargg**
- `package_show `  API supports GET method instead  of POST.
 - Implemented list_pages for CKAN Pages

### CODE REVIEW

**Comment by sagargg** [comment]
@anuveyatsu can you review and merge it.  Also CI failed to build.  Didn't understand,  never work on that. Could you fix that too.

**Comment by anuveyatsu** [comment]
@sagargg is this PR different from what we have already here #134 ?

**Comment by sagargg** [comment]
@anuveyatsu   both are same.  Close either of one.

**Comment by starsinmypockets** [comment]
Closing as duplicate https://github.com/datopian/frontend-v2/pull/138

**Pull request closed without merging**
