### PR TITLE
Fix/save dl link

### PR DESCRIPTION
**Pull request by starsinmypockets**

### CODE REVIEW

**Comment by anuveyatsu** [comment]
@starsinmypockets I guess we could have a better name, e.g., `originalPath` or `initialPath`

**Comment by starsinmypockets** [comment]
@anuveyatsu `resourcePath` ?

**Comment by starsinmypockets** [comment]
Maybe just `downloadLink`

**Comment by anuveyatsu** [comment]
@starsinmypockets `downloadLink` or just `download`?

**Comment by starsinmypockets** [comment]
I think `downloadPath` since this is what we are using this for

**Comment by starsinmypockets** [comment]
@anuveyatsu Can I merge this?

**Pull request merged**
